### ISSUE TITLE
Input 200 pitch/loudness, why I got only one block samples, not 200 blocks?  

### ISSUE THREAD

**Issue by Teaonly** [acids-ircam/ddsp_pytorch#24]
I have try to building a end-to-end re-synthesize demo, like code 

```
import torch

model = torch.jit.load("ddsp_pretrained_mytraining.ts")

##pitch = torch.randn(1, 200, 1)  
pitch = load_pitch_from_extract()
##loudness = torch.randn(1, 200, 1)
loudness = load_loudness_from_extract()

audio = model(pitch, loudness)

##save audio to wav

```
Why audio tensor size is (1, 512), not (1, 51200) ? Which block_size of model is 512.

**Comment by caillonantoine** [comment]
It seems that you have exported your trained model with the argument `--realtime true`, which downsamples the conditioning signal so that the synthesized audio's dimensionality stays coherent (see here https://github.com/acids-ircam/ddsp_pytorch/blob/master/export.py#L36).

If you want to use DDSP in an offline manner, I would suggest not to use the `realtime` flag !

**Comment by Teaonly** [comment]
Thanks, I can modify config before foward.

'''
model.realtime = False
'''
